version: '3.3'
services:

  wolfie-app:
    build:
      context: .
    environment: 
      DATABASE_URL: '${POSTGRES_URL}'
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres
    networks:
      - awesome

  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    networks:
      - awesome

  pgadmin:
    image: dpage/pgadmin4:6.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '5656:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always
    networks:
      - awesome

volumes:
  pgadmin-data:

networks:
  awesome:
    driver: bridge